import { Sixtyfour } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { ThemeProvider } from "@/theme/themeProvider";
import { Toaster } from "@/components/ui/sonner";

import backgroundImg from "@/assets/background.png";
import CustomPrivyProvider from "@/privy/privyProvider";
import AudioComponent from "@/components/audio/audioComponent";

const sixtyfour = Sixtyfour({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "BugsMachine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sixtyfour.className}>
        <CustomPrivyProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Toaster />
            <AudioComponent backgroundImg={backgroundImg}>{children}</AudioComponent>
          </ThemeProvider>
        </CustomPrivyProvider>
      </body>

    </html>
  );
}
